name: Deploy to EKS


on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 \
        | docker login --username AWS --password-stdin 946774551819.dkr.ecr.eu-north-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t node-hello:${{ github.run_number }} .

    - name: Tag image
      run: |
        docker tag node-hello:${{ github.run_number }} \
        946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    - name: Push image
      run: |
        docker push 946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    - name: Configure kubeconfig
      run: |
        aws eks --region eu-north-1 update-kubeconfig --name yaswanth-cluster

    - name: Deploy application
      run: |
        kubectl set image deployment/hello-yaswanth \
        hello-container=946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    - name: Verify rollout
      run: |
        kubectl rollout status deployment/hello-yaswanth --timeout=180s

    # âœ… Configure credentials again for rollback
    - name: Configure AWS credentials for rollback
      if: failure()
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-north-1

    - name: Rollback deployment if failed
      if: failure()
      run: |
        echo "Deployment failed. Rolling back to previous stable version..."
        aws eks --region eu-north-1 update-kubeconfig --name yaswanth-cluster
        kubectl rollout undo deployment/hello-yaswanth
        echo "Rollback completed successfully."
