name: Deploy to EKS

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-north-1

    # Login to ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 \
        | docker login --username AWS --password-stdin 946774551819.dkr.ecr.eu-north-1.amazonaws.com

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t node-hello:${{ github.run_number }} .

    # Tag image
    - name: Tag image
      run: |
        docker tag node-hello:${{ github.run_number }} \
        946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    # Push image
    - name: Push image
      run: |
        docker push 946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    # Configure kubectl
    - name: Update kubeconfig
      run: |
        aws eks --region eu-north-1 update-kubeconfig --name yaswanth-cluster

    # Deploy new image
    - name: Deploy new version
      run: |
        kubectl set image deployment/hello-yaswanth \
        hello-container=946774551819.dkr.ecr.eu-north-1.amazonaws.com/node-hello:${{ github.run_number }}

    # Wait for deployment
    - name: Verify rollout
      run: |
        kubectl rollout status deployment/hello-yaswanth --timeout=120s

    # Rollback if deployment fails
    - name: Rollback on failure
      if: failure()
      run: |
        echo "Deployment failed. Rolling back to previous stable version..."
        kubectl rollout undo deployment/hello-yaswanth
