name: CI-CD EKS Deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ECR_REPOSITORY: hello-yaswanth
      DEPLOYMENT_NAME: hello-yaswanth
      CONTAINER_NAME: hello-container

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Get AWS Account ID automatically
      - name: Get AWS Account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build image using commit SHA
      - name: Build Docker image
        run: docker build -t app:${{ github.sha }} .

      # Tag image with version + latest
      - name: Tag Docker image
        run: |
          docker tag app:${{ github.sha }} \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

          docker tag app:${{ github.sha }} \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Push both tags
      - name: Push Docker image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Connect to cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Deploy new image version
      - name: Deploy new version
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
          $CONTAINER_NAME=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      # Monitor rollout
      - name: Verify rollout
        run: kubectl rollout status deployment/$DEPLOYMENT_NAME
