name: Deploy to EKS

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region "${{ secrets.AWS_REGION }}" \
        | docker login --username AWS --password-stdin \
        "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"

    - name: Build Docker image
      run: |
        docker build -t "${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}" .

    - name: Tag Docker image
      run: |
        docker tag "${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}" \
        "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Push Docker image
      run: |
        docker push \
        "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Configure kubeconfig
      run: |
        aws eks --region "${{ secrets.AWS_REGION }}" \
        update-kubeconfig --name "${{ secrets.EKS_CLUSTER_NAME }}"

    - name: Deploy new version
      run: |
        kubectl set image deployment/hello-yaswanth \
        hello-container="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Verify deployment & rollback
      run: |
        echo "Waiting for rollout..."

        if kubectl rollout status deployment/hello-yaswanth --timeout=180s; then
          echo "Deployment successful. Old pods removed."
        else
          echo "Deployment failed. Showing crash info..."

          kubectl get pods -o wide

          FAILED_POD=$(kubectl get pods \
            --field-selector=status.phase!=Running \
            -o jsonpath="{.items[0].metadata.name}")

          kubectl describe pod $FAILED_POD || true
          kubectl logs $FAILED_POD || true

          echo "Rolling back..."
          kubectl rollout undo deployment/hello-yaswanth
          exit 1
        fi
