name: Deploy to EKS

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region "${{ secrets.AWS_REGION }}" | docker login --username AWS --password-stdin "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"

    - name: Build Docker image
      run: |
        docker build -t "${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}" .

    - name: Tag Docker image
      run: |
        docker tag "${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}" \
        "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Push Docker image
      run: |
        docker push "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Configure kubeconfig
      run: |
        aws eks --region "${{ secrets.AWS_REGION }}" update-kubeconfig --name "${{ secrets.EKS_CLUSTER_NAME }}"

    - name: Deploy application
      run: |
        kubectl set image deployment/hello-yaswanth \
        hello-container="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}"

    - name: Wait rollout
      run: |
        kubectl rollout status deployment/hello-yaswanth --timeout=120s || true

    - name: Validate deployment
      run: |
        echo "Checking pod health..."

        CRASHING=$(kubectl get pods | grep CrashLoopBackOff || true)

        if [ -n "$CRASHING" ]; then
          echo "❌ Deployment failed — CrashLoopBackOff detected"

          echo "---- POD STATUS ----"
          kubectl get pods -o wide

          POD=$(kubectl get pods | grep CrashLoopBackOff | awk '{print $1}')

          echo "---- POD DETAILS ----"
          kubectl describe pod $POD

          echo "---- APPLICATION LOGS ----"
          kubectl logs $POD || true

          echo "Rolling back..."
          kubectl rollout undo deployment/hello-yaswanth

          echo "Cleaning failed ReplicaSets..."
          kubectl get rs -o name | grep hello-yaswanth | xargs kubectl delete || true

          echo "Rollback complete. Old version restored."
          exit 1
        else
          echo "✅ Deployment successful."
        fi
